import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./infraestucture/context/auth-provider";

export const metadata: Metadata = {
  title: "Volunteer Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-b from-[#7cb3f1] to-white via-[#D0E2F7] via-70%">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
 